[resolvcache]
dumplog  = "/var/cache/luids/dns/cache-dump.log"
dumpsecs = 60
expire   = 7200

[collectlog]
file      = "/var/lib/luids/dns/cache-collect.log"

[server-check]
listenuri = "tcp://0.0.0.0:5892"

[server-collect]
listenuri = "tcp://0.0.0.0:5891"
