[resolvcache]
logfile  = "/var/lib/luids/dns/cache.log"
expire   = 7200

[resolvcache.dump]
file  = "/var/lib/luids/dns/cache-dump.log"
secs  = 60

[server-check]
listenuri = "tcp://0.0.0.0:5892"

[server-collect]
listenuri = "tcp://0.0.0.0:5891"
