[resolvcache]
expire   = 7200

[resolvcache.trace]
file  = "/var/lib/luids/dns/resolvcache.log"

[resolvcache.dump]
file  = "/var/lib/luids/dns/cache-dump.log"
secs  = 60

[server]
listenuri = "tcp://0.0.0.0:5891"
